profiles:
  h1:
    asia_session:
      start_h: 0
      end_h: 8
      tz_source: "UTC"
    post_session:
      breakout_lookahead_h: 6
      confirm_with_body: true
    atr:
      window: 14
    formatting:
      pip_size: 0.0001
      tick_size: 0.0
sweep:
  confirm_mode: "body"
  reclaim_mode: "body_back"
  reclaim_n_bars: 3
  min_pen_atr_mult: 0.10
  max_pen_atr_mult: 1.00
  max_duration_bars: 10
  link_events_window_bars: 20
  atr_window: 14
  pip_size: 0.0001
  tick_size: 0.0
  quality_weights:
    penetration_norm: 0.30
    fast_reclaim: 0.35
    context_eq: 0.20
    asia_alignment: 0.15
  quality_grades:
    A: [0.75, 1.00]
    B: [0.55, 0.75]
    C: [0.00, 0.55]
eq_cluster:
  eq_atr_tol: 0.06
  alt_pip_tol: 0.0
  body_confirm: false
  max_dupe_bars: 1
  use_swings_gate: false

  merge_overlap: true
  merge_gap_atr_mult: 0.25
  min_touch_count: 2
  min_age_bars: 5

  weights:
    touches: 0.40
    age: 0.20
    tightness: 0.25
    cleanliness: 0.15

  pip_size: 0.0001
  tick_size: 0.0
  atr_window: 14
  annotate_asia: true
