profiles:
  h1:
    use_only_strong_swings: true
    swing_merge_atr_mult: 0.10
    bos_break_mult_atr: 0.15
    bos_leg_min_atr_mult: 0.55
    atr_window: 14
    event_cooldown_bars: 3
    confirm_with_body_only: true
  m15:
    use_only_strong_swings: true
    swing_merge_atr_mult: 0.10
    bos_break_mult_atr: 0.18
    bos_leg_min_atr_mult: 0.50
    atr_window: 14
    event_cooldown_bars: 3
    confirm_with_body_only: true
